/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "canbench-duoSidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "CANBENCH-DUO Overview (v1.1)"
    },
    {
      "type": "category",
      "label": "User Manual",
      "link": {
        "type": "doc",
        "id": "user-manual/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "user-manual/quick-start",
          "label": "Quick Start"
        },
        {
          "type": "doc",
          "id": "user-manual/spectrum-analyser-setup",
          "label": "Spectrum-Analyser Setup"
        },
        {
          "type": "doc",
          "id": "user-manual/measurement-procedure",
          "label": "Measurement Procedure"
        },
        {
          "type": "doc",
          "id": "user-manual/status-led",
          "label": "Status LED"
        },
        {
          "type": "doc",
          "id": "user-manual/common-pitfalls",
          "label": "Common Pitfalls"
        },
        {
          "type": "doc",
          "id": "user-manual/interpreting-results",
          "label": "Interpreting Results"
        }
      ]
    },
    {
      "type": "category",
      "label": "Quick Reference",
      "link": {
        "type": "doc",
        "id": "quick-reference/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "quick-reference/bom",
          "label": "Bill of Materials"
        },
        {
          "type": "doc",
          "id": "quick-reference/connectors",
          "label": "External Connectors"
        },
        {
          "type": "doc",
          "id": "quick-reference/led-states",
          "label": "LED States"
        }
      ]
    },
    {
      "type": "doc",
      "id": "tasks",
      "label": "Tasks"
    },
    {
      "type": "category",
      "label": "Circuit Design",
      "link": {
        "type": "doc",
        "id": "circuit-design/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "circuit-design/lisn-supply-path",
          "label": "LISN Supply Path"
        },
        {
          "type": "doc",
          "id": "circuit-design/lisn-measurement-ports",
          "label": "LISN Measurement Ports"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-cm-port",
          "label": "CAN Common-Mode Port"
        },
        {
          "type": "doc",
          "id": "circuit-design/connectors-and-mechanical",
          "label": "Connectors & Mechanical"
        },
        {
          "type": "doc",
          "id": "circuit-design/power-indicator-led",
          "label": "Power Indicator LED"
        },
        {
          "type": "doc",
          "id": "circuit-design/pcb-markings",
          "label": "PCB Markings & Compliance"
        }
      ]
    },
    {
      "type": "category",
      "label": "Housing",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "housing"
        }
      ]
    },
    {
      "type": "category",
      "label": "Compliance",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "compliance"
        }
      ]
    }
  ]
};

export default sidebars;
