/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "mdd400Sidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "MDD400 Overview (v2.9)"
    },
    {
      "type": "doc",
      "id": "quick-reference",
      "label": "Quick Reference"
    },
    {
      "type": "doc",
      "id": "tasks",
      "label": "Tasks"
    },
    {
      "type": "category",
      "label": "Circuit Design",
      "link": {
        "type": "doc",
        "id": "circuit-design/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "circuit-design/esp32-module",
          "label": "ESP32 Module"
        },
        {
          "type": "doc",
          "id": "circuit-design/led-indicator",
          "label": "LED Indicator"
        },
        {
          "type": "doc",
          "id": "circuit-design/programming-socket",
          "label": "Programming Socket"
        },
        {
          "type": "doc",
          "id": "circuit-design/power-supplies",
          "label": "Power Supplies"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-bus-power",
          "label": "CAN Bus Power Protection"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-transceiver",
          "label": "CAN Transceiver"
        },
        {
          "type": "doc",
          "id": "circuit-design/display-interface",
          "label": "Display Interface"
        },
        {
          "type": "doc",
          "id": "circuit-design/power-monitor",
          "label": "Power Monitor"
        },
        {
          "type": "doc",
          "id": "circuit-design/ambient-light-sensor",
          "label": "Ambient Light Sensor"
        },
        {
          "type": "doc",
          "id": "circuit-design/temperature-sensor",
          "label": "Temperature Sensor"
        },
        {
          "type": "doc",
          "id": "circuit-design/buzzer-driver",
          "label": "Buzzer Driver"
        },
        {
          "type": "doc",
          "id": "circuit-design/legacy-serial",
          "label": "Legacy Serial Interface"
        },
        {
          "type": "doc",
          "id": "circuit-design/pcb-markings",
          "label": "PCB Markings & Compliance"
        }
      ]
    },
    {
      "type": "category",
      "label": "Firmware",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "firmware"
        }
      ]
    },
    {
      "type": "category",
      "label": "Housing",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "housing"
        }
      ]
    },
    {
      "type": "category",
      "label": "Compliance",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "compliance"
        }
      ]
    }
  ]
};

export default sidebars;
