/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "canbench-truezSidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "CANBENCH-TRUEZ Overview (v1.1)"
    },
    {
      "type": "category",
      "label": "User Manual",
      "link": { "type": "doc", "id": "user-manual/index" },
      "items": [
        { "type": "doc", "id": "user-manual/quick-start", "label": "Quick Start" },
        { "type": "doc", "id": "user-manual/spectrum-analyser-setup", "label": "Spectrum-Analyser Setup" },
        { "type": "doc", "id": "user-manual/measurement-procedure", "label": "Measurement Procedure" },
        { "type": "doc", "id": "user-manual/common-pitfalls", "label": "Common Pitfalls" },
        { "type": "doc", "id": "user-manual/interpreting-results", "label": "Interpreting Results" }
      ]
    },
    {
      "type": "category",
      "label": "Quick Reference",
      "link": { "type": "doc", "id": "quick-reference/index" },
      "items": [
        { "type": "doc", "id": "quick-reference/bom", "label": "Bill of Materials" },
        { "type": "doc", "id": "quick-reference/connectors", "label": "External Connectors" }
      ]
    },
    {
      "type": "doc",
      "id": "tasks",
      "label": "Tasks"
    },
    {
      "type": "category",
      "label": "Circuit Design",
      "link": { "type": "doc", "id": "circuit-design/index" },
      "items": [
        { "type": "doc", "id": "circuit-design/cm-dm", "label": "CM & DM Separator" },
        { "type": "doc", "id": "circuit-design/connectors", "label": "Connectors & Markings" }
      ]
    },
    {
      "type": "category",
      "label": "Housing",
      "items": [ { "type": "autogenerated", "dirName": "housing" } ]
    },
    {
      "type": "category",
      "label": "Compliance",
      "items": [ { "type": "autogenerated", "dirName": "compliance" } ]
    }
  ]
};

export default sidebars;
