/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "wti400Sidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "WTI400 Overview (v1.2)"
    },
    {
      "type": "doc",
      "id": "quick-reference",
      "label": "Quick Reference"
    },
    {
      "type": "category",
      "label": "Circuit Design",
      "link": {
        "type": "doc",
        "id": "circuit-design/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "circuit-design/esp32-module",
          "label": "ESP32 Module"
        },
        {
          "type": "doc",
          "id": "circuit-design/power-supplies",
          "label": "Power Supply"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-bus-power",
          "label": "CAN Bus Power"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-transceiver",
          "label": "CAN Transceiver"
        },
        {
          "type": "doc",
          "id": "circuit-design/wind-interface",
          "label": "Wind Interface"
        },
        {
          "type": "doc",
          "id": "circuit-design/motion-sensor",
          "label": "Motion Sensor"
        },
        {
          "type": "doc",
          "id": "circuit-design/button",
          "label": "Button Input"
        },
        {
          "type": "doc",
          "id": "circuit-design/led-indicator",
          "label": "LED Indicator"
        },
        {
          "type": "doc",
          "id": "circuit-design/legacy-serial",
          "label": "Legacy Serial Interface"
        }
      ]
    },
    {
      "type": "category",
      "label": "Firmware",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "firmware"
        }
      ]
    },
    {
      "type": "category",
      "label": "Housing",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "housing"
        }
      ]
    },
    {
      "type": "category",
      "label": "Compliance",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "compliance"
        }
      ]
    }
  ]
};

export default sidebars;
