/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  "canbench-duoSidebar": [
    {
      "type": "doc",
      "id": "index",
      "label": "CANBENCH-DUO Overview (v1.2)"
    },
    {
      "type": "doc",
      "id": "quick-reference",
      "label": "Quick Reference"
    },
    {
      "type": "doc",
      "id": "tasks",
      "label": "Tasks"
    },
    {
      "type": "category",
      "label": "Circuit Design",
      "link": {
        "type": "doc",
        "id": "circuit-design/index"
      },
      "items": [
        {
          "type": "doc",
          "id": "circuit-design/lisn-supply-path",
          "label": "LISN Supply Path"
        },
        {
          "type": "doc",
          "id": "circuit-design/lisn-measurement-ports",
          "label": "LISN Measurement Ports"
        },
        {
          "type": "doc",
          "id": "circuit-design/can-cm-port",
          "label": "CAN Common-Mode Port"
        },
        {
          "type": "doc",
          "id": "circuit-design/connectors-and-mechanical",
          "label": "Connectors & Mechanical"
        },
        {
          "type": "doc",
          "id": "circuit-design/power-indicator-led",
          "label": "Power Indicator LED"
        },
        {
          "type": "doc",
          "id": "circuit-design/pcb-markings",
          "label": "PCB Markings & Compliance"
        }
      ]
    },
    {
      "type": "category",
      "label": "Firmware",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "firmware"
        }
      ]
    },
    {
      "type": "category",
      "label": "Housing",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "housing"
        }
      ]
    },
    {
      "type": "category",
      "label": "Compliance",
      "items": [
        {
          "type": "autogenerated",
          "dirName": "compliance"
        }
      ]
    }
  ]
};

export default sidebars;
