/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mdd400Sidebar: [{type: 'autogenerated', dirName: '.'}],
  wti400Sidebar: [{type: 'autogenerated', dirName: '.'}],
  canbenchDuoSidebar: [{type: 'autogenerated', dirName: '.'}],
  canbenchTruezSidebar: [{type: 'autogenerated', dirName: '.'}],
  aboutSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
